# Generated by Django 5.2.11 on 2026-08-06 05:30

import user_app.actions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_feedback_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=(
                    ("normal", user_app.actions.normal),
                    ("friend_apply", user_app.actions.friend_apply),
                ),
                default="normal",
                max_length=25,
            ),
        ),
    ]
