# Generated by Django 5.2.11 on 2026-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_notification_action_data_notification_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[("normal", "普通通知"), ("friend_apply", "好友申请")],
                default="normal",
                max_length=25,
            ),
        ),
    ]
