# Generated by Django 5.2.11 on 2026-08-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_alter_notification_action_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("normal", "notification"),
                    ("friend_apply", "friend_apply"),
                    ("apply_check", "apply_check"),
                ],
                default="normal",
                max_length=25,
            ),
        ),
    ]
