# Generated by Django 5.2.11 on 2026-07-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
