# Generated by Django 5.2.9 on 2026-07-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs_app', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='username',
        ),
    ]
