# Generated by Django 5.2.11 on 2026-07-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs_app', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='feedback',
        ),
    ]
