# Generated by Django 5.2.11 on 2026-07-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs_app', '0005_remove_notification_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
    ]
